### ISSUE TITLE
How to pronounce keyv?

### ISSUE THREAD

**Issue by kaneda** [lukechilds/keyv#104]
We're arguing about how this project is supposed to be pronounced. I believe it is supposed to be "key vee" (i.e., key value), others are saying "keev," which is correct?

**Comment by lukechilds** [comment]
Haha, I'm sorry but the correct pronunciation is "keev".

Are you using Keyv for something interesting at Salesforce?

**Comment by jbegleiter-sf** [comment]
Hey @lukechilds,

Commenting from my "official" Salesforce Github. We use Keyv in the Salesforce Commerce SDK ( https://github.com/SalesforceCommerceCloud/commerce-sdk ) indirectly (via cacheable-request).

Cheers,
Josh

**Comment by lukechilds** [comment]
Nice, thanks Josh.
