### ISSUE TITLE
Time remaining before delete of a key

### ISSUE THREAD

**Issue by HiiZun** [lukechilds/keyv#106]
hello i want to get a time remaining before a key must be deleted, it's possible ?
and we can know the start time ?

**Comment by chroventer** [comment]
You can use the raw option to obtain the `ttl` and subtract the ttl from `Date.now()` to obtain the time remaining:
```javascript
const data = await keyv.get('key', { raw: true });
const timeRemaining = Date.now() - data.ttl;
console.log(timeRemaining);
```

**Comment by HiiZun** [comment]
oh yes  thank you verry much !
i will close the issue

**Comment by HiiZun** [comment]
i get just a error: `SyntaxError: Unexpected identifier`
