### ISSUE TITLE
Keys set with a TTL are not deleted

### ISSUE THREAD

**Issue by soundstep** [lukechilds/keyv#108]
I created a PR, mergeable probably: https://github.com/lukechilds/keyv/pull/107

To reproduce:
```
const store = new Map();
const keyv = new Keyv({ store, ttl: 100 });
keyv.set('foo1', 'bar1');
keyv.set('foo2', 'bar2');
// wait for the TTL and check the store size
```

Result: `store.size` is 2
Expected: `store.size` should be 0

I originally found the issue with a memory leak in the [cacheable-response](https://www.npmjs.com/package/cacheable-response) package, which use keyv.

**Comment by lukechilds** [comment]
Closed via https://github.com/lukechilds/keyv/pull/107
