### ISSUE TITLE
Slow adapter fails the test-suite

### ISSUE THREAD

**Issue by dev-araisan** [lukechilds/keyv#109]
I am writing a cloud storage adapter, but this adapter has a slow response and takes more than 1 second for set and get together, so the cache is deleted in the ttl expires test and failed.

https://github.com/lukechilds/keyv-test-suite/blob/dc2cbd227c3c00df13fedaca0f4e05aab1469c77/src/api.js#L30

Is it possible to add a timekeeper before the set?

**Comment by lukechilds** [comment]
Relying on the real world time on the tests like it is currently is not ideal. Ideally anywhere time is used in the test the value should be mocked.

So if you want to add an extra mock then yeah, definitely!

I don't have time to work on this now but feel free to open a PR.
