### ISSUE TITLE
TTL Not Setting

### ISSUE THREAD

**Issue by Hamster-0001** [lukechilds/keyv#110]
When setting a TTL with Keyv/Mongo while using arguments, not hard coding a TTL. The TTL defaults to "never expire" instead of accepting the provided time (even if the number is in ms)

Code provided below:
```    let time = args[1]
    
    if (!toAdd) return message.channel.send('Please provide a user ID');
    if (!time) return message.channel.send('Please send a time in ms')
    if (time < 6000) return message.channel.send('Please provide a time more than 1 minute')

    blacklistDB.on('error', err => console.log('Connection Error', err));
    
    await blacklistDB.set(toAdd, `expires in ${time}ms`, time);```

**Comment by lukechilds** [comment]
Can you create a reproducible code example I can test? From your provided code I have no idea what the `toAdd` or `time` values are.

When you have a reproducible example can you test with the in memory storage adapter to see if the issue is in Keyv or `keyv-mongo`?

**Comment by Hamster-0001** [comment]
I tested it with the storage adapter `keyv-mongo` and the TTL is now running properly.
