### ISSUE TITLE
Is a leaderboard possible?

### ISSUE THREAD

**Issue by ZerioDev** [lukechilds/keyv#114]
Good evening,

I've only been using the module for a short time (great), but how do I make a ranking? I haven't figured it out. I used quick.db before and here is my old code : https://pastebin.com/ycZAZC8M

But I'm using a dedicated money file : 

`const DATAMONEY = new Keyv("sqlite://path/to/../../data/money.sql")`

Unlike quick.db, where everything is saved to a single file.

Is it possible to do this on Keyv?
If so, I'd like some help.

Good evening to you!

**Comment by lukechilds** [comment]
Keyv is key-value store, if you can implement your behaviour with a key-value store then Keyv can probably do it, if you need more advance query capabilities then Keyv is probably not what you want.

The API and behaviour is extensively documented in the readme, if you read through that you should have a good idea of Keyvs functionality and if your use case is possible. https://github.com/lukechilds/keyv
