### ISSUE TITLE
Storing a Map object as value, returns object instead of Map

### ISSUE THREAD

**Issue by Magicrafter13** [lukechilds/keyv#126]
```javascript
catDB.set('test', new Map())
  .then(() => {
    catDB.get('test')
    .then(obj => console.log(obj.has('f')))
    .catch(console.error);
  })
.catch(console.error);
```
Was trying to figure out the issue with a project I'm working, eventually realized I was getting an error, stating that `.has` was not a function (of the thing be returned by `.get`), so I poked around in a debugger, and realized that what I was getting was not a Map, but just an object apparently. Wrote this short test bit to make sure.

I don't necessarily think this is a bug with Keyv, and more than likely just a lack of understanding on my part, but either way I'm unsure of how to proceed. I looked into seeing if I could cast the object to a Map but with no luck.

**Comment by ayntee** [comment]
`Map` is not supported by JSON.serialize(), it is converted into an empty object.
You can customize the JSON.serialize() and JSON.parse() methods and pass it as serialize and deserialize to the Keyv instance to support `Map`.

Read more: https://github.com/lukechilds/keyv#custom-serializers

**Comment by Magicrafter13** [comment]
Ah, that's too bad. Thank you though.

I think I'll just use an array instead, I don't expect there to be *too* many values, so speed shouldn't be a big issue I guess.
