### ISSUE TITLE
Un-Maintained Repo

### ISSUE THREAD

**Issue by MattA-Official** [lukechilds/keyv#132]
@lukechilds It would appear that this project is no longer being maintained. I would suggest either cleaning up the issues and pull requests that have been sitting around for months or handing management over to someone else.

I understand that at the moment everything works as intended for the most part, so there is no urgent need to fix anything but that doesn't mean there is no need to review the open issues and pull requests.

I also recognize that you may be busy working on other things, this would be another reason to hand over management to another person. I am looking forward to a response regarding the future of keyv.

<hr>

**Comment by Kikobeats** [comment]
hey @MattA-Official, some users are recreating this in a new organization, merging all the pending PRs, implementing all the features requested.

Check https://github.com/keyvhq/keyv 🙂

**Comment by MattA-Official** [comment]
@Kikobeats that's good to see. I'll be checking it out and potentially contributing. There is still the issue of sorting out the npm registry though.

**Comment by Kikobeats** [comment]
in fact, we were forced to move all the things into a new organization because we don't have npm permissions for publishing this package.

so in the future, instead of `npm install keyv`, you will perform a `npm install @keyvhq/keyv`
