### ISSUE TITLE
Switch to namespaced modules.

### ISSUE THREAD

**Issue by DylanPiercey** [lukechilds/keyv#14]
Great list of modules here. I think it would be a good idea to switch to [scoped modules](https://docs.npmjs.com/misc/scope) with a [public org](https://www.npmjs.com/docs/orgs/).

There are several benefits here:

* There is no chance that someone could steal a package name.
* Users can more trust just packages without worrying about squaters/malware.
* You can more easily give other developers access/control of individual repo's and manage it all from one org.

**Comment by lukechilds** [comment]
Yeah, I had considered this (+ GitHub Org) before actually, just wasn't sure if anyone apart from me was ever gonna care about this module to warrant the extra effort.

Fully agree with your points though, I'm really busy at the moment but will get on this ASAP.

**Comment by DylanPiercey** [comment]
Awesome, let me know if you need help with anything. Glad to do so!

**Comment by lukechilds** [comment]
Thanks 👍

**Comment by lukechilds** [comment]
@DylanPiercey This has been a major pain in the ass but it's happening 🎉

**Comment by DylanPiercey** [comment]
Awesome! This is definitely something to get out of the way earlier as it will save some bigger pains later. Thanks for your work on this! 🎉😄

**Comment by lukechilds** [comment]
@DylanPiercey This should be all sorted, published as v2.0.0 as old storage adapter package names won't be automatically picked up.

https://github.com/lukechilds/keyv/releases/tag/v2.0.0

**Comment by DylanPiercey** [comment]
@lukechilds awesome. I've already switched some of my modules that are depending on it 👍.
