### ISSUE TITLE
IPC storage adapters

### ISSUE THREAD

**Issue by Muhaah** [lukechilds/keyv#24]
Is there a adapter that uses the build in Node-IPC for storing data in memory.
I'm searching for something like [memored](https://github.com/PaquitoSoft/memored) but with namespaces.

**Comment by MySidesTheyAreGone** [comment]
If you look at the API, it's trivial to wrap memored in a Key storage adapter. Look at @keyv/redis as an example; substitute redis logic with memored logic and you're good to go.

Namespaces, btw, are simply pretended to the key so they don't need any particular structure.

**Comment by MySidesTheyAreGone** [comment]
Err GitHub's css just... Died... So I can't correct the previous message. s/pretended/prepended

**Comment by lukechilds** [comment]
@Muhaah No plans for an official IPC adapter, but as @MySidesTheyAreGone says it would be fairly simple to implement a third-party adapter.
