### ISSUE TITLE
Add custom serializer option

### ISSUE THREAD

**Issue by lukechilds** [lukechilds/keyv#26]
Currently `JSONB.stringify`/`JSONB.parse` is used for serializing/deserializing to support a wide range JavaScript Types.

Allowing users to set a custom a custom serializer function will allow for cleaner usage with custom data structures and enable performance improvements for people who don't need all the type support `JSONB` provides.

Syntax should look something like:

```js
const Keyv = require('keyv');
const { serialize, deserialize } = require('my-serializer');

const keyv = new Keyv({ serialize, deserialize });
```

Previous discussion in #22

**Comment by MySidesTheyAreGone** [comment]
I should be able to get this done around next week if nobody else is working on it.

**Comment by lukechilds** [comment]
@MySidesTheyAreGone That would be brilliant, thanks!

It's only a tiny change, just literally have not had the time.

**Comment by MySidesTheyAreGone** [comment]
My thoughts exactly, it's the kind of thing you can outsource safely to Italy :D

**Comment by lukechilds** [comment]
Or to a rabbit on the internet.

**Comment by MySidesTheyAreGone** [comment]
A screaming Italian rabbit on the Internet will fix your code for free! I looked at the other issue, but no luck, I know nothing about typescript (or any weird preprocessed stuff). Ping me if you get other small tasks/issues you want me to take off your hands. I have a large-ish project depending on keyv and a smaller one is on the way so I don't mind.

**Comment by lukechilds** [comment]
Thanks, appreciate it, I will.

**Comment by MySidesTheyAreGone** [comment]
I'm back! Is this issue OK? Anything else needed?

**Comment by lukechilds** [comment]
Hi, sorry, there are a few extra things needed from my paid project so I haven't been able to dedicate as much time to OSS as I'd of liked recently. Should be all finished up very soon. Reviewing the latest changes now.

**Comment by MySidesTheyAreGone** [comment]
The trip was fantastic! I should be able to fix the tests tomorrow, assuming I understand your review - I'm still quite the amateur

**Comment by lukechilds** [comment]
Closed by https://github.com/lukechilds/keyv/pull/33
