### ISSUE TITLE
file storage

### ISSUE THREAD

**Issue by Kikobeats** [lukechilds/keyv#31]
ideal for avoid use mongo/redis on development, just plain json for temporal data.

**Comment by lukechilds** [comment]
There is a third party file storage adapter here: https://github.com/zaaack/keyv-file

**Comment by Kikobeats** [comment]
Oh. Should it be listed in the official documentation?

**Comment by lukechilds** [comment]
Yeah, probably should actually.

I'll add it when I get a chance, moving abroad tomorrow so may be a few days until I have the time. Feel free to submit  a PR if you want.
