### ISSUE TITLE
Propose `Keyv.prototype.memoize`

### ISSUE THREAD

**Issue by Moeriki** [lukechilds/keyv#34]
I'd like to propose a solution for a common pattern. At least for me.

**Usage**

```js
const cachedRequest = keyv.memoize(request);

cachedRequest('http://example.com').then(() => { /* result */ });
// later
cachedRequest('http://example.com').then(() => { /* cached result */ });
```

**Implementation**

```js
/**
 * @param {function}        func
 * @param {object}          [opts]
 * @param {function}        [opts.resolver=identity]
 * @param {function|number} [opts.ttl]
 * @return {Promise}
 */
Keyv.prototype.memoize = function memoize(func, { resolver, ttl }) {
  return (...args) => {
    const key = resolver ? resolver(...args) : args[0];
    return this.get(key).then((storedValue) => {
      if (storedValue !== undefined) {
        return storedValue;
      }
      return Promise.resolve(func(...args)).then((value) => {
        if (value !== undefined) {
          return this.set(key, value, typeof ttl === 'function' ? ttl(value) : value)
            .then(() => value)
          ;
        }
        return value;
      });
    });
  };
};
```

**Comment by lukechilds** [comment]
Thanks for submitting an issue. Keyv is just supposed to be a storage compatibility layer, therefore I consider memoize functionality outside the scope of Keyv.

However, I'm sure a lot of Keyv users would benefit from this functionality. I'd recommend you create you own package, `keyv-memoize` (or similar) and depend on Keyv for the storage adapter side. Then you can implement your own memoize logic, and if someone wants to implement the memoize logic in a different way they can build their own package. Keyv should be unopinionated on how it's used.

Let me know if you decide to build this, it'd be great to have a link in the readme to your project.

Btw, if you are specifically using this for caching requests, check out [`cacheable-request`](https://github.com/lukechilds/cacheable-request). It was what I originally wrote Keyv for and has loads of extra features to properly handle RFC compliant HTTP caching.

**Comment by Moeriki** [comment]
Sure thing Luke.

Request was thing that came to mind. Not my use-case.

https://github.com/Moeriki/memoized-keyv

**Comment by lukechilds** [comment]
That was fast, `memoized-keyv` looks great!

I'm pretty stacked out with work right now but I've created a new issue (https://github.com/lukechilds/keyv/issues/35) to remind me to add this to the readme.

Awesome work!
