### ISSUE TITLE
Plans to support maximum size and cleanup of expired entries

### ISSUE THREAD

**Issue by olivr70** [lukechilds/keyv#56]
Hi,

as keyv is a very strong proposition for implementing a cache, are there any plans to : 
- support setting a maximum size, which would trigger eviction of oldest keys
- support a simple cleanup of expired keys

or may be those have been ruled for simplicity ? in that case, it feels like at least a way to iterate on keys would allow for a wrapper to implement periodic cleanup. If mimicking Map, this could mean implementing keys() as returning an Iterable

The trouble being it needs to be implmented in all stores.

Anyway, your work is very elegant and promising.

**Comment by MySidesTheyAreGone** [comment]
Luke's stance has been to keep the core simple and let this kind of tasks be implemented via subclassing. However the core is currently missing stuff you need to implement what you're talking about. The only self-cleaning solutions must rely on redis or Mongo.

**Comment by lukechilds** [comment]
Hi @olivr70 

Thanks for taking the time to send your thoughts over.

As @MySidesTheyAreGone mentioned, I'd like to keep the core as simple as possible.

Extra functionality should be built as storage adapters or as a new library that uses Keyv under the hood. However not enough functionality is exposed from Keyv at the moment to do that much.

I am planning to expose more of the internals, however paid work has been limiting the amount of time I can work on Keyv at the moment.

You will probably find this issue helpful: https://github.com/lukechilds/keyv/issues/36

**Comment by lukechilds** [comment]
But more specifically, if your use case is just:

>- support setting a maximum size, which would trigger eviction of oldest keys
>- support a simple cleanup of expired keys

You can already do that by backing Keyv with [keyv-redis](https://github.com/lukechilds/keyv-redis) or [quick-lru](https://github.com/sindresorhus/quick-lru).

**Comment by olivr70** [comment]
@lukechilds @MySidesTheyAreGone 
Thanks for your anwsers. It felt that way reading the repo.

I will look at a store based solution then. Probably will start with quick-lru for simplicity. 

The thing is I would probably benefit from pretty wide cache with a large number of nearly static items, and would rather not have it in memory. But I still have to do the maths and testing to validate the use of a large cache. Hence my interest for keyv, which allows switching caching strategies based on experience.

From my point of view, this issue can be closed. Thanks.
