### ISSUE TITLE
Create DB if doesn't exist?

### ISSUE THREAD

**Issue by rraallvv** [lukechilds/keyv#65]
Is there a way to ask the adapter to create the table if it doesn't exist?

**Comment by rraallvv** [comment]
Sorry, if I'm missing something really obvious but this snippet of code throws and error indicating `UnhandledPromiseRejectionWarning: Error: Unknown database 'my_table'` 
```
var Keyv = require('keyv');
var keyv = new Keyv("mysql://user:pass@localhost:3306/my_table");
```

**Comment by adityapatadia** [comment]
This issue is applicable to https://github.com/lukechilds/keyv-mysql. Can you open new issue there?

**Comment by rraallvv** [comment]
Done! https://github.com/lukechilds/keyv-mysql/issues/37
I'm closing this then.
@adityapatadia thanks for pointing that out.
