### ISSUE TITLE
Ability to use TTL on Maps

### ISSUE THREAD

**Issue by szmarczak** [lukechilds/keyv#66]
The default store is `new Map()`. It has no(?) TTL support. But we could do something like:

```js
if (store instanceof Map) {
	store.timers = {};
	store._set = store.set;
	store.set = (key, value, ttl) => {
		clearTimeout(store.timers[key]);
		store.set(key, value);
		store.timers[key] = setTimeout(() => {
			delete store.timers[key];
			store.delete(key);
		}, ttl);
	};
}
```

**Comment by lukechilds** [comment]
TTL does work for `new Map()` it just doesn't remove them as soon as the TTL expires. If you try to get a property after it's expired then it will remove the entry and return as if it never existed.

So as far as the application is concerned, TTLs function fine. But there is obviously a memory overhead as expired entries are kept in memory until they are requested again. I'm definitely open to reducing this if possible in a reliable way.

The solution you propose would reduce memory usage if the user is indeed using a Map. However I'm not sure `store instanceof Map` is a safe check.

What if they were using a storage adapter that extended Map but used a remote data source and had multiple application servers? Server A sets with a 1 hour TTL and then 30 minutes later server B sets with a one hour TTL. Another 30 minutes later, server A will delete server Bs entry even though it's still valid for another 30 minutes.

**Comment by szmarczak** [comment]
> TTL does work for new Map() it just doesn't remove them as soon as the TTL expires. If you try to get a property after it's expired then it will remove the entry and return as if it never existed.

Can you provide any example? I tried but it still doesn't work. I couldn't find anything related on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set).

> What if they were using a storage adapter that extended Map but used a remote data source and had multiple application servers? Server A sets with a 1 hour TTL and then 30 minutes later server B sets with a one hour TTL. Another 30 minutes later, server A will delete server Bs entry even though it's still valid for another 30 minutes.

Well, then these servers aren't synchronized, they're just separate storages.

**Comment by TehShrike** [comment]
@szmarczak see this code in the `get()` function: https://github.com/lukechilds/keyv/blob/de2e7a2ffc4a5007569b62a31956d7b692a011e7/src/index.js#L62-L65

**Comment by lukechilds** [comment]
@szmarczak TTL is checked again inside Keyv to catch all stores that don't implement it natively.

>Well, then these servers aren't synchronized, they're just separate storages.

They are if they use the same remote data source.

**Comment by szmarczak** [comment]
>  TTL is checked again inside Keyv to catch all stores that don't implement it natively.

Well, sorry for my confusion. I thought it was done only natively. :+1:

> Another 30 minutes later, server A will delete server Bs entry even though it's still valid for another 30 minutes.

So as I understand this server A is responsible for managing server B. If server A sets on server B an item after 30min delay, then it should delete that after 30 min too. If it doesn't - badly implemented server. Not our fault.

Let me give an example to your implementation:

Server A sets with a 1 hour TTL and then 30 minutes later server B sets with a one hour TTL. Another 30 minutes later, server A will delete server Bs (through performing `.get()`) entry even though it's still valid for another 30 minutes.

It is no different than my implementation except yours checks the timeout on `.get()`.

**Comment by lukechilds** [comment]
>So as I understand this server A is responsible for managing server B.

@szmarczak Not quite, server A doesn't manage Server B. Keyv will store the TTL timestamp with the data and send the TTL to stores that support native TTLs. Stores that support TTLs natively will than handle deleting the entries themselves, stores that don't will store the data indefinitely, however when Keyv receives an entry from a store it will double check the TTL, if it's expired it will manually delete it from the store and return undefined as if it never existed.

A thorough example:

**If server A and server B both use a remote store that supports native TTLs (e.g Redis)**

Server A sets a value that expires after 30 mins, Redis will delete the value internally after 30 mins.

Server B then sets the same value to expire after 40 mins. Redis will now not delete untill 40 mins has elapsed.

The following behaviour is identical for server A or B:

Get after 25 mins: Redis returns value, Keyv double checks TTL and returns value.

Get after 35 mins: Redis returns value, Keyv double checks TTL and returns value.

Get after 45 mins: Redis returns undefined, Keyv returns undefined.

Get after 55 mins: Redis returns undefined, Keyv returns undefined.

**If server A and server B both use a remote store that doesn't support native TTLs (e.g MySQL)**

Server A sets a value that expires after 30 mins, MySQL will keep the value indefinitely.

Server B then sets the same value to expire after 40 mins, MySQL will still keep the value indefinitely.

The following behaviour is identical for server A or B:

Get after 25 mins: MySQL returns value, Keyv double checks TTL and returns value.

Get after 35 mins: MySQL returns value, Keyv double checks TTL and returns value.

Get after 45 mins: MySQL returns value, Keyv double checks TTL, noticed it has expired, deletes the value from MySQL and returns undefined.

Get after 55 mins: MySQL returns undefined, Keyv returns undefined.

**Using Map**

>>Well, then these servers aren't synchronized, they're just separate storages.

>They are if they use the same remote data source.

That's correct.

Map functions exactly the same as using a store without native TTL support, however it should only ever be used for a single server. There is no communication between servers. If you use a Map with multiple instances running they each have their own isolated Keyv instance and no data is shared.

**Comment by szmarczak** [comment]
I get it now. But it's still vulnerable to this:

**If server A and server B both use a remote store that supports native TTLs (e.g Redis)**

Server A sets a value that expires after 30 mins, Redis will delete the value internally after 30 mins.

Server B then sets the same value to expire after 40 mins. Redis will now not delete untill 40 mins has elapsed.

The following behaviour is identical for server A or B:

Get after 25 mins: Redis returns value, Keyv double checks TTL and returns value.

Get after 35 mins: **Someone performs `.get()`. Keyv noticed the TTL has expired and deletes the value and returns undefined.**

Get after **38 mins**: Redis returns undefined, Keyv returns undefined.

Get after 45 mins: Redis returns undefined, Keyv returns undefined.

**Comment by szmarczak** [comment]
If the Map is responsible for setting elements on server B with extended TTL, the `delete` function should know that and delete that after 10 mins. Otherwise: badly implemented map, not our concern.

**Comment by lukechilds** [comment]
>Get after 35 mins: **Someone performs `.get()`. Keyv noticed the TTL has expired and deletes the value and returns undefined.**

The TTL hasn't expired in this scenario because the second `.set()` by server B updated the TTL in Redis to be 40 mins so Keyv won't delete the value.

>If the Map is responsible for setting elements on server B with extended TTL, the `delete` function should know that and delete that after 10 mins. Otherwise: badly implemented map, not our concern.

I think there might still be some confusion, not quite sure what you mean here but if Redis is being used as a store, there is no Map.

**Comment by szmarczak** [comment]
Ok, I believe I understand this: for example two Keyv instances connected to one database. Pardon my previous comments. You're right. I'll try to figure something out...

**Comment by lukechilds** [comment]
What is the issue you're having?

**Comment by elliot40404** [comment]
You can always monkeypatch
```js
keyv.has = async (key) => !!(await keyv.get(key));
```
