### ISSUE TITLE
Consider serializing Sets

### ISSUE THREAD

**Issue by dandv** [lukechilds/keyv#68]
Would this be within scope?

**Comment by lukechilds** [comment]
Not within this package but I've had it on my todo list for an external package for a while.

Essentially a JSON encode/decode lib with support for all modern native JS types.

**Comment by lukechilds** [comment]
Found on an abandoned Trello board of module ideas from over a year ago:

```
better-json

exposes encode/decode methods
(maybe also alias to stringify/parse for standard lib JSON compat)
can be extended with type plugins
type plugins have a fn to detect a type and then a serializer/deserializer fn
look at json-buffer for inspiration
should come with buffer/map/set type plugins included by default
use this in Keyv
```

**Comment by adityapatadia** [comment]
Closing this as it's not applicable for this package.
