### ISSUE TITLE
keyv doesn't work in pnpm monorepo

### ISSUE THREAD

**Issue by dandv** [lukechilds/keyv#70]
Trying to use keyv and @keyv/mongo works with npm (duh), [pnpm](https://pnpm.js.org), but not if the project is a pnpm workspace. The error is "Error: Cannot find module '@keyv/mongo'".

Repro repo at https://github.com/dandv/pnpm-monorepo-keyv

Any idea what might cause this?

**Comment by lukechilds** [comment]
Ahh, so seems like `pnpm` is hijacking the Node.js dependency resolution algorithm somehow.

I wouldn't really consider this a bug in Keyv so I'll close this issue. Glad you got it sorted though. Thanks for reporting, hopefully this issue will help anyone else who gets stuck using Keyv with `pnpm`. 👍

**Comment by matzkoh** [comment]
I saw this error when I deployed my app to vercel.
I simply added one line and it worked without any other changes.

````
import Keyv from 'keyv'
import '@keyv/mongo' // <===
```
