### ISSUE TITLE
Add ".all" to Keyv

### ISSUE THREAD

**Issue by ThatTonybo** [lukechilds/keyv#76]
I find myself needing an `all` function for uses like a leaderboard for my users, right now I'm having to bypass Keyv and select from sqlite manually, which for a database wrapper isn't appreciated.

Can we get `<Keyv>.all()` added? Or possibly some kind of filtering too?

**Comment by lukechilds** [comment]
This is already planned: https://github.com/lukechilds/keyv/issues/40
