### ISSUE TITLE
Error when trying to run on RPI3 with all dependencies installed

### ISSUE THREAD

**Issue by YourPalNicky** [lukechilds/keyv#97]
I have this exact code working on my PC, but when ran on an RPI3 (All dependencies are installed and up to date) it hits an error and closes.

Error Shown Below:

internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module '/home/pi/.djsbots/discordbot/node_modules/@keyv/sqlite/node_modules/sqlite3/lib/binding/node-v79-linux-arm/node_sqlite3.node'
Require stack:
- /home/pi/.djsbots/discordbot/node_modules/@keyv/sqlite/node_modules/sqlite3/lib/sqlite3.js
- /home/pi/.djsbots/discordbot/node_modules/@keyv/sqlite/src/index.js
- /home/pi/.djsbots/discordbot/node_modules/keyv/src/index.js
- /home/pi/.djsbots/discordbot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/.djsbots/discordbot/node_modules/@keyv/sqlite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.djsbots/discordbot/node_modules/@keyv/sqlite/node_modules/sqlite3/lib/sqlite3.js',
    '/home/pi/.djsbots/discordbot/node_modules/@keyv/sqlite/src/index.js',
    '/home/pi/.djsbots/discordbot/node_modules/keyv/src/index.js',
    '/home/pi/.djsbots/discordbot/index.js'
  ]

**Comment by lukechilds** [comment]
Looks like this is an issue with the sqlite3 npm module. Are you using the @keyv/sqlite storage adapter?

**Comment by YourPalNicky** [comment]
Uh, no. I have installed keyv & @heyv/sqlite, but no storage adapter was
ever installed.

**Comment by lukechilds** [comment]
Yes, @keyv/sqlite is a storage adapter.

I can see in sqlite3 they have added some changes related to arm builds. Maybe this will fix your problem.

I've just released a new version of @heyv/sqlite (2.0.2) which uses the latests version of sqlite3. Can you give that a go and let me know if that works for you?

**Comment by YourPalNicky** [comment]
Yeah let me boot it up real quick, for some reason no matter what I tried, a linux-arm file would never install with a npm i @keyv/sqlite.

**Comment by YourPalNicky** [comment]
If that fixed it, maybe I'm doing something wrong. Just ran `npm i @keyv/sqlite` (Installed 2.0.2)

Got the same error:

internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module '/home/pi/.djsbots/discordbot/node_modules/sqlite3/lib/binding/node-v79-linux-arm/node_sqlite3.node'
Require stack:
- /home/pi/.djsbots/discordbot/node_modules/sqlite3/lib/sqlite3.js
- /home/pi/.djsbots/discordbot/node_modules/@keyv/sqlite/src/index.js
- /home/pi/.djsbots/discordbot/node_modules/keyv/src/index.js
- /home/pi/.djsbots/discordbot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/.djsbots/discordbot/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.djsbots/discordbot/node_modules/sqlite3/lib/sqlite3.js',
    '/home/pi/.djsbots/discordbot/node_modules/@keyv/sqlite/src/index.js',
    '/home/pi/.djsbots/discordbot/node_modules/keyv/src/index.js',
    '/home/pi/.djsbots/discordbot/index.js'
  ]
}

**Comment by lukechilds** [comment]
Try nuking the entire `node_modules` folder and do `npm install` to make sure we definitely have a clean install.

**Comment by YourPalNicky** [comment]
Will do, give a moment...

**Comment by YourPalNicky** [comment]
I am currently stuck loading on this last section:
Logs below:




pi@pi:~/.djsbots/discordbot $ npm i

> sqlite3@4.1.0 install /home/pi/.djsbots/discordbot/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v79-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and node@13.1.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/home/pi/.djsbots/discordbot/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3280000/sqlite3.o

pi@pi:~/.djsbots/discordbot $ npm i

> sqlite3@4.1.0 install /home/pi/.djsbots/discordbot/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v79-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and node@13.1.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/home/pi/.djsbots/discordbot/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3280000/sqlite3.o

**Comment by lukechilds** [comment]
That's building sqlite from source, just give it a while.

**Comment by YourPalNicky** [comment]
Before I have waited ~20 minutes and it has eventually timed out, if it takes that long then I can let it sit

**Comment by lukechilds** [comment]
I see you're using Node.js v13. You could try using Node.js v12 instead. That's an LTS release so more likely to have pre-compiled binary available.

It might just be that they don't have any bins for your arm chip though so you'll have to build from source no matter which Node.js version you use.

**Comment by YourPalNicky** [comment]
I can try both, how am I able to downgrade to v12?

**Comment by lukechilds** [comment]
Depends how you installed Node.js.

If you install [nvm](https://github.com/nvm-sh/nvm) you can do `nvm install 12`.

nvm sets the version per shell session not globally, so you can have one session running v12 and another session running v13 simultaneously and test them together.

**Comment by YourPalNicky** [comment]
Alright, will troubleshoot more tomorrow. I will reply to this thread of I figure anything else out.

**Comment by YourPalNicky** [comment]
I ran just finished the npm i, seems to be working fine now. I will test tomorrow more. The console log seems a bit odd and it got cut off due to length. I'll attach it below-
[saved.txt](https://github.com/lukechilds/keyv/files/3861942/saved.txt)

**Comment by lukechilds** [comment]
That looks fine to me, it's just dumping all the sqlite3 compilation output to stdout so you can see what's going on.

I'll close this issue as it appears to be resolved. Feel free to re-open if you discover that isn't the case.
