### ISSUE TITLE
operation keyv

### ISSUE THREAD

**Issue by GlauberF** [lukechilds/keyv#98]
I could not understand well the use for keyv, have some article explaining better.
My doubt, does he maintain direct communication with the backend (mongoDB) making both sides with updated data, client and backend?

**Comment by Kikobeats** [comment]
keyv is pretty similar to a traditional LRU cache, plus it's compatible with a lot of databases adapters being possible not only storing the data on memory but also on MySQL, PostgreSQL, Redis, etc...

Storage adapters are so simple and they only can retrieve data or update data.

If you need something like a feed of real-time changes you can open a stream connection over your storage adapter, but keyv doesn't do something similar by default.

I hope my comment addresses your concern, please be free to reply and share your user case 🙂

**Comment by GlauberF** [comment]
thank you very much

when you change in local cache does it apply this change to the backend bank through the adapters?

another question, do you have any material to tell me about realtime change feed for MongoDB.
where could i use in conjunction with keyv?
